# Generated by Django 3.0 on 2019-12-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeip',
            name='time',
            field=models.BigIntegerField(default=1575744919),
        ),
    ]
