# Generated by Django 3.0 on 2019-12-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20191207_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeip',
            name='ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activeip',
            name='time',
            field=models.BigIntegerField(default=0),
        ),
    ]
